replicaCount: 1

image:
  repository: danelnas/ip_app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

containerPort: 5001

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
